### ISSUE TITLE
flags | hide untranslated languages

### ISSUE THREAD

**Issue by dankYoff** [dotabod/frontend#107]
Hide languages with less than a certain % of translation (for example, <=40%)

![Image](https://user-images.githubusercontent.com/91318807/223381521-a52e2511-4cc0-4b06-86a8-dc2c24897395.png)

OR

Show languages that are already released and can be used

![Image](https://user-images.githubusercontent.com/91318807/223389501-1f470b90-7271-401b-a8b6-f60267ad4d15.png)

**Comment by Geczy** [comment]
i dont wanna hide them because i want people to select their language if they see it, then they will be able to help with finishing the translations 

and the hide button is useless because once you selected your language, why bother going back into the select box?
