### ISSUE TITLE
show streamers, who now stream and used bot

### ISSUE THREAD

**Issue by dankYoff** [dotabod/frontend#26]
Cool to place it on the home page
https://dota2protracker.com/
![зображення](https://user-images.githubusercontent.com/91318807/212004291-8c758372-d0f6-4609-a518-6083641fff49.png)

wizebot
![зображення](https://user-images.githubusercontent.com/91318807/212751532-e5f608cd-51e6-42b1-a486-5570102bf77d.png)

tsuwari
![зображення](https://user-images.githubusercontent.com/91318807/212751584-2ff73b68-b6e5-4e05-983c-69e261f3ef00.png)

idk need you show this
![Image](https://user-images.githubusercontent.com/91318807/215636387-55d184ac-36e0-4895-a7b3-afb59c7bd965.png)

**Comment by dankYoff** [comment]
I think it will be cool to place it on the home page

**Comment by dankYoff** [comment]
![зображення](https://user-images.githubusercontent.com/91318807/212751532-e5f608cd-51e6-42b1-a486-5570102bf77d.png)

**Comment by dankYoff** [comment]
idk need you show this

![Image](https://user-images.githubusercontent.com/91318807/215636387-55d184ac-36e0-4895-a7b3-afb59c7bd965.png)

**Comment by Geczy** [comment]
we now show streamers who are using the bot live ! 

top streamers, and random streamers
