### ISSUE TITLE
doesn't crosses out added emotions

### ISSUE THREAD

**Issue by dankYoff** [dotabod/frontend#27]
Does not delete added emotions to the channel. After a while, when I logged in again, they were deleted, but not all of them (maybe because they are cached)
![зображення](https://user-images.githubusercontent.com/91318807/212017385-a11cf6b3-2ede-4eb0-ba43-55cb6698e9e7.png)

**Comment by dankYoff** [comment]
after some time, when I unlinked the old accounts and linked them again, everything worked
![зображення](https://user-images.githubusercontent.com/91318807/212019635-2fb9dc4b-f772-470b-ba79-67e92d845619.png)

**Comment by dankYoff** [comment]
what i tried to do:
1) exit and enter back
2) appoint and remove dotabod from the moderator
3) close the tab and log in to the account again

**Comment by dankYoff** [comment]
after a while after all the manipulations everything works, but automatically he didn't want to do it

**Comment by vsmelnikov** [comment]
maybe should use manual checkboxes? i think it's will be more usefull

**Comment by dankYoff** [comment]
emotions are not updated when you either remove them or add them to dashboard emotions
![зображення](https://user-images.githubusercontent.com/91318807/212600735-c123ec7d-9a56-4dba-89fc-bcf6ba88a22a.png)
![зображення](https://user-images.githubusercontent.com/91318807/212600683-20b99d2b-cacf-41aa-8a9b-316d7682c6f5.png)

**Comment by Geczy** [comment]
yeah it does cross out, but it takes some time because bttv and 7tv cache the results. so once you come back in an hour it will be okay

**Comment by dankYoff** [comment]
Okay, that's how it works. But when you added an emotion to the channel, and then you delete it from the dashboard of betterttv or 7tv - it does not appear as the emotion you deleted (that is, it remains crossed out). I think this is a rather unnecessary mistake that does not need to be fixed and there are much more important things to do

**Comment by Geczy** [comment]
i've just added this feature !
