### ISSUE TITLE
Fixing and adding certain commands to the dashboard

### ISSUE THREAD

**Issue by dankYoff** [dotabod/frontend#31]
- [ ] Using certain commands even when the stream is disabled (like !setmmr 1234, !lg, !lgs)
- [x] Add commands that are still missing by type (!hero, !medal, !toggle)
- [x]  !about = !dotabod, so maybe add this to descriprion command
- [x]  Animation of the opening of teams (it is quite unpleasant, it is better to make a smooth opening)
- [x]  Change the description (supplement) of certain commands (like !modsonly) It would be good if the command description was used from 1 file and it would go very well with the idea of ​​translating the dashboard

**Comment by Geczy** [comment]
about is not dotabod anymore, so will not add that one

**Comment by Geczy** [comment]
i will add alias to every command

![image](https://user-images.githubusercontent.com/1036968/214159052-18b154ae-883f-46e1-86bc-900f2726f596.png)

**Comment by dankYoff** [comment]
> i will add alias to every command

I don't think it's necessary, but in principle I like this idea, it's unlikely that people will get confused between the teams and some people will find this team particularly individual
