### ISSUE TITLE
popular questions

### ISSUE THREAD

**Issue by dankYoff** [dotabod/frontend#33]
Dotabod keeps saying play a match, no steam id?
1) Follow Setup -> [Step 2](https://dotabod.com/dashboard)
2) Check the correctness of the path to the `gamestate_integration_dotabod.cfg` file folder and the `-gamestateintegration` command in the game launch options. Play a match with bots and re-enter the game
3) Your account is already connected to another Twitch account. To delete it, write to the dotabod help channel and confirm that this is really your Steam account

wl lose dont refresh

**Comment by Geczy** [comment]
maybe have to update this translation to include more info about checking gsi
