### ISSUE TITLE
Add description to !ping and !wl

### ISSUE THREAD

**Issue by dankYoff** [dotabod/frontend#36]
!ping - Maybe someone will say that I'm useless [FeelsStrongMan](https://betterttv.com/emotes/58facc4aaffae60eac088397), but I'm not your teammate [EZ](https://betterttv.com/emotes/5590b223b344e2c42a9e28e3)
!wl - Find out about the total number of wins and losses. Disabling this command will hide these statistics in the stream overlay

**Comment by Geczy** [comment]
where does description show? in dashboard?

**Comment by dankYoff** [comment]
yeap
