### ISSUE TITLE
customize mmr

### ISSUE THREAD

**Issue by dankYoff** [dotabod/frontend#37]
### BEFORE
![зображення](https://user-images.githubusercontent.com/91318807/214509157-d0a08480-77cd-46b9-a4b1-93bca0573853.png)
### AFTER
![зображення](https://user-images.githubusercontent.com/91318807/214520431-0d88eaa8-9a72-42a7-af8f-876312b92494.png)

**Comment by dankYoff** [comment]
or like this
![зображення](https://user-images.githubusercontent.com/91318807/214521790-878bf8c3-93c9-4052-b33d-8c323c3400f2.png)

**Comment by dankYoff** [comment]
![зображення](https://user-images.githubusercontent.com/91318807/214531703-bf0c0ec3-b880-4c12-8e67-a4c579fef860.png)

**Comment by dankYoff** [comment]
![зображення](https://user-images.githubusercontent.com/91318807/214567555-934ac9c3-60dc-4f92-9552-62c06bead728.png)

**Comment by dankYoff** [comment]
image take from https://dota2.fandom.com/wiki/Abaddon
![зображення](https://user-images.githubusercontent.com/91318807/214570393-162461a4-6893-48ad-a046-94165dbca311.png)

**Comment by dankYoff** [comment]
You can make a pop-up picture that will give a hint of what to do, as on the main page of preview

Private data - show a picture where this setting is located
Enter your mmr - show a picture where mmr is located
Incorrectly entered mmr - indicated a large rating (indicate which mmr +- 200-500 should be entered)
Rank is not displayed - A picture where it is explained that you need to play calibration or 20 matches in a week for it to appear

I think this will help reduce the number of frequently asked questions

![зображення](https://user-images.githubusercontent.com/91318807/215069170-c4d22b6d-ffdd-4912-8a35-7154cd23fd2d.png)

**Comment by dankYoff** [comment]
move this to prieview?

![Image](https://user-images.githubusercontent.com/91318807/215564009-bd6e2bfa-e0c2-4265-8270-c0f5a5afb1e0.png)

**Comment by dankYoff** [comment]
![Image](https://user-images.githubusercontent.com/91318807/215565801-ca57663c-d298-48ea-a6f8-450cd67457a7.png)

**Comment by Geczy** [comment]
added mmr preview to toggles

**Comment by dankYoff** [comment]
![зображення](https://user-images.githubusercontent.com/91318807/215578056-b0a00881-a033-4b37-8a31-d5262e0d75fa.png)

**Comment by dankYoff** [comment]
Lasthit/Deny (LH/D)
