### ISSUE TITLE
Support page

### ISSUE THREAD

**Issue by dankYoff** [dotabod/frontend#38]

**Comment by dankYoff** [comment]
![зображення](https://user-images.githubusercontent.com/91318807/214840883-973c16e0-3dd4-4a89-85fa-814300527783.png)

**Comment by Geczy** [comment]
done! ty for idea



![Image](https://user-images.githubusercontent.com/1036968/215499402-aeb5465b-1b12-4b5d-ba40-363aad7e3a14.png)
