### ISSUE TITLE
1 click to add dotabod to mod сhannel

### ISSUE THREAD

**Issue by dankYoff** [dotabod/frontend#42]
Nightbot has a function that you press 1 button and the bot joins your chat as a moderator
![зображення](https://user-images.githubusercontent.com/91318807/215078528-aac91c37-d50c-4266-a28d-cf897e2d8580.png)
![зображення](https://user-images.githubusercontent.com/91318807/215078453-4870411f-a85d-415f-9325-5bb6933e6aa7.png)

**Comment by Geczy** [comment]
this is just to make setup _slightly_ easier

instead, perhaps this step can just show 1 click button 2 paste text



![Image](https://user-images.githubusercontent.com/1036968/215355688-4ca1c232-14f7-47af-a67d-3cd8763365e6.png)

**Comment by dankYoff** [comment]
I thought it was easy to implement, but if it takes a long time (it's better not to do it, because it's very easy to do it yourself anyway)

**Comment by Geczy** [comment]
i added this implementation !
