### ISSUE TITLE
dashbord (ideas)

### ISSUE THREAD

**Issue by dankYoff** [dotabod/frontend#44]

**Comment by dankYoff** [comment]
For example, add information about updates, new, interesting facts.
![зображення](https://user-images.githubusercontent.com/91318807/215259146-f676b834-c163-492a-ad25-cf1dec45c844.png)

or, for example, add avatars and nicknames of people who donate and support the project (as well as the developer of 9kmrbot, thereby showing respect to him)
video from https://navi.gg/ua

You can do it in the form of a picture or a running line

https://user-images.githubusercontent.com/91318807/215259679-e849a93c-3a54-48cd-8f41-3159f07a778a.mp4

**Comment by dankYoff** [comment]
When you don't have enough space to create new features, I offer the following option, as in the photo. I think it's pretty cute

- Add useful links that are not yet available
- Move all components to the left
- Log out button, add to profile (if needed)
- Pop-up window (a preview of how to use and where the link takes you)

![зображення](https://user-images.githubusercontent.com/91318807/215260136-8394b4ca-a9cd-412e-a486-6da181183a08.png)

**Comment by dankYoff** [comment]
![зображення](https://user-images.githubusercontent.com/91318807/215260410-21188f93-3aee-4699-8874-feb2ba0d56da.png)

**Comment by Geczy** [comment]
rather do feature cards, grayed out, unclickable, coming soon badge
