### ISSUE TITLE
mobile issues

### ISSUE THREAD

**Issue by dankYoff** [dotabod/frontend#47]
- [x] Does not open the link in the window, you need to refresh the page for the content to appear

![Image](https://user-images.githubusercontent.com/91318807/219903981-64413a7c-6bc5-48e5-9c77-2c8673f7fc6c.png)

![Image](https://user-images.githubusercontent.com/91318807/219903985-dadd0c56-30a0-4af4-a831-99f268657187.png)

- [x] small/big badge

![Image](https://user-images.githubusercontent.com/91318807/217384570-48800b81-9c2d-43f8-a3ac-1c39b7431044.png)

I think its look better
![зображення](https://user-images.githubusercontent.com/91318807/217383854-fd9f838b-5acc-4ce3-8fae-94e4989ae206.png)

- [x] not showing logo
![зображення](https://user-images.githubusercontent.com/91318807/217381911-7405e14a-fcd8-4da0-9080-7b995d2c6d3e.png)

- [x] picture overlaps the text

![зображення](https://user-images.githubusercontent.com/91318807/217382139-2e0e9f5d-1ee6-4536-881c-08c67d21e0a0.png)

- [x] When you go to the dotabot, this sign is constantly hanging and you need to reload the page to make it disappear

![Image](https://user-images.githubusercontent.com/91318807/221086367-ba5cea4b-cce4-47bb-b166-20a64cf8a618.png)

**Comment by dankYoff** [comment]
Version for PC
![Screenshot_2023-01-30-04-06-16-477_com android chrome](https://user-images.githubusercontent.com/91318807/215372771-93e17dc5-032d-409c-bb2d-796b2fa73e04.jpg)

**Comment by dankYoff** [comment]
![Screenshot_2023-02-02-02-13-19-818_com android chrome](https://user-images.githubusercontent.com/91318807/216198483-9b8efb2e-819f-4ee6-a62d-5c9e6c8e8b8a.jpg)
![Screenshot_2023-02-02-02-13-10-352_com android chrome](https://user-images.githubusercontent.com/91318807/216198488-31410e2f-ed74-4d89-b7bb-b565ca51f3fb.jpg)

**Comment by Geczy** [comment]
>  When you go to the dotabot, this sign is constantly hanging and you need to reload the page to make it disappear
 i didnt se this issue

but the others are all fixed ty
