### ISSUE TITLE
open a link in new tab

### ISSUE THREAD

**Issue by dankYoff** [dotabod/frontend#48]
For mainpage and dashboard - github and discord (and else in the future)

![Image](https://user-images.githubusercontent.com/91318807/215475966-739a495e-5fce-4246-9195-8ef967200e38.gif)

**Comment by Geczy** [comment]
oh yeah good idea, it needs to be a new link

**Comment by dankYoff** [comment]
_blank
It seems to me that it will be more convenient for the user and he will not have to open the bot manually 3-4 times, and he himself will decide whether this tab is necessary or not
