### ISSUE TITLE
custom scroll on main page

### ISSUE THREAD

**Issue by dankYoff** [dotabod/frontend#50]
before

![Image](https://user-images.githubusercontent.com/91318807/215622135-aad922c1-eb74-4b35-a434-2429084bc9cb.png)

after

![Image](https://user-images.githubusercontent.com/91318807/215622215-68aa85df-4e1f-4620-8ad9-99517dddab47.png)

**Comment by Pranav4399** [comment]
Hello maintainers ! In case the issue hasn't been taken already, I can take up this. But before that, main page refers to [this](https://dotabod.com/) right?

**Comment by Geczy** [comment]
Yes that is it! Thank you for helping

**Comment by Pranav4399** [comment]
Hello. Created a new PR - https://github.com/dotabod/frontend/pull/126.

**Comment by Pranav4399** [comment]
Hello. I believe this issue can be closed. [PR](https://github.com/dotabod/frontend/pull/126) for reference.
