### ISSUE TITLE
cooming soon

### ISSUE THREAD

**Issue by dankYoff** [dotabod/frontend#67]
![Image](https://user-images.githubusercontent.com/91318807/216482166-4ebcccb9-4354-4c27-8f4f-6b675c97135f.png)

![Image](https://user-images.githubusercontent.com/91318807/216484411-6fdd92dc-bf4f-4c05-bde4-629540c4e904.png)

**Comment by dankYoff** [comment]
![Image](https://user-images.githubusercontent.com/91318807/216482166-4ebcccb9-4354-4c27-8f4f-6b675c97135f.png)

**Comment by Geczy** [comment]
This is done
