### ISSUE TITLE
notp chatter (works even when you turn it off)

### ISSUE THREAD

**Issue by dankYoff** [dotabod/frontend#71]
![зображення](https://user-images.githubusercontent.com/91318807/216637538-2f6ad4a1-d63c-4687-8b3e-23791e1ccb50.png)

**Comment by dankYoff** [comment]
![Image](https://user-images.githubusercontent.com/91318807/216637471-55efe7fe-d462-456a-a0d3-98f9a06567e8.png)

**Comment by Geczy** [comment]
fixed
