### ISSUE TITLE
correct overlay display while wathcing match

### ISSUE THREAD

**Issue by dankYoff** [dotabod/frontend#76]
For example, [https://github.com/andsfonseca/dota2-rpc-client](https://github.com/andsfonseca/dota2-rpc-client ) it can determine what stage of the game it is, maybe it can be implemented before the game. So that the overlay appears already after the loading screen

![Image](https://user-images.githubusercontent.com/91318807/216741370-9f9791a5-fdf9-4047-b159-3d1bb08aad52.png)

![Image](https://user-images.githubusercontent.com/91318807/216741375-297566fc-e2bd-4e36-a23b-91bd05945b6d.png)

**Comment by Geczy** [comment]
this app just uses gsi as well https://github.com/andsfonseca/dota2-rpc-client/blob/master/include/services/DotaService.h

maybe i can look at this service for some ideas. 

https://github.com/andsfonseca/dota2-rpc-client/blob/master/src/services/DotaService.cpp#L44

i think there are more states that dotabod is not looking at yet, like loading state, so maybe i just have to add them

good reference to look at, ty

**Comment by Geczy** [comment]
cant do this one, no api for when they're spectating and found a match
