### ISSUE TITLE
add dotabod in game overlay

### ISSUE THREAD

**Issue by dankYoff** [dotabod/frontend#77]
I think the main problem of 9kmrbot was the slow development and everyone knew him only because he spammed phrases in the chat. Therefore, for greater popularity, you can add the Dotabot logo to the OBS overlay

You can add a gif or video that will draw attention to it0

https://user-images.githubusercontent.com/91318807/216782292-77a2d6a0-626f-4357-be7d-3d8183793faa.mp4

![Image](https://user-images.githubusercontent.com/91318807/216772675-18f1346a-d289-456f-b2d5-dc7aad925965.png)

![Image](https://user-images.githubusercontent.com/91318807/216782191-c623b39d-4049-45f1-ba14-8b466597a672.png)

**Comment by Geczy** [comment]
i wont be adding ads to dotabod, i think its not necessary because dotabod is already spamming in the chat, and anyone can click the username to find more information. lots of streamers wont want this either, they will get mad if i start showing ads on their twitch streams

**Comment by dankYoff** [comment]
I think this feature can be added when premium (if you want it to be disabled, and for streamers who have <500 viewers, it won't be considered an advertisement, it will only indicate what kind of bot it is
