### ISSUE TITLE
Fill in the missing space

### ISSUE THREAD

**Issue by dankYoff** [dotabod/frontend#79]
![Image](https://user-images.githubusercontent.com/91318807/217356113-a6bdbe04-05f4-4175-b463-32285a43bf5f.png)

![Image](https://user-images.githubusercontent.com/91318807/217358298-3281b57f-f2ac-4fb6-b14f-10a17f700f98.png)

**Comment by Geczy** [comment]
just finished 🆗

**Comment by Geczy** [comment]
maybe cta to new feature add instead of secret ft
