### ISSUE TITLE
neutral flags for np (overlay and command)

### ISSUE THREAD

**Issue by dankYoff** [dotabod/frontend#89]
For example, Ukrainians (like Ghostik, Dendi, terrorize) do not want to see the flags of Russians or Iranians, which are associated with the current war. I think there are also certain circumstances for other streamers that make them not want to see certain flags on their streams

Therefore, you can add the option to select neutral flags for the stream (that is, the streamer chooses the country that will be with a neutral flag)

https://liquipedia.net/dota2/Swedenstrong
![Image](https://user-images.githubusercontent.com/91318807/220253370-d54a09f4-2f83-498f-992e-5ddcec9fd83a.png)

**Comment by dankYoff** [comment]
These are not only Russian flags for Ukrainians, it means that each streamer can choose which flags to show and which to hide. A person from the United States can hide the flag of China, a person from Belarus can hide the flag of Ukraine, etc. This is just an additional feature, not an interference in political or military actions between countries.

**Comment by Geczy** [comment]
i dont think there's any need to hide a chinese flag as an american unless it was politically or racially motivated, this feature wont be added

**Comment by dankYoff** [comment]
@Geczy If you disable this function, will it hide flags in the !np command? Or will it just hide the overlay of famous players?
![image](https://user-images.githubusercontent.com/91318807/221640945-185d8e16-8a0e-4f5f-8499-f619d9a7900e.png)

**Comment by Geczy** [comment]
no, but i think its a good idea. you can open a new issue for disabling flags entirely as a new feature
