### ISSUE TITLE
flags | show countries as a table

### ISSUE THREAD

**Issue by dankYoff** [dotabod/frontend#91]
Show languages in a table instead of 1 column

![Image](https://user-images.githubusercontent.com/91318807/220260836-51fc524c-31a0-46ab-9147-ea8c2cbacf13.png)

**Comment by Geczy** [comment]
now that % is added its better to show in a single list i think

since it got longer 



![Image](https://user-images.githubusercontent.com/1036968/223500598-b4d52ca7-83d9-484f-87a9-d6e1c5aed3e2.png)
